name: End-to-end tests 🧪

on: [push]

jobs:
  robot-run:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false
          
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12'
          